INFO:root:Running add with arguments (2, 3)
INFO:root:Running add with arguments (2, 3)
INFO:root:Running sub with arguments (3, 4)
INFO:root:Running add with arguments (2, 3)
INFO:root:Running sub with arguments (3, 4)
INFO:root:Running square with arguments (5,)
INFO:root:Running cube with arguments (4, 6)
INFO:root:Running add with arguments (2, 3)
INFO:root:Running sub with arguments (3, 4)
INFO:root:Running square with arguments (5,)
INFO:root:Running cube with arguments (4,)
INFO:root:Running add with arguments (2, 3)
INFO:root:Running sub with arguments (3, 4)
INFO:root:Running square with arguments (5,)
INFO:root:Running cube with arguments (4,)
